# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# azure-pipelines.yml
trigger:
- main

variables:
  imageName: 'flaskapp'

stages:
- stage: BuildAndPush
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'nagapavani23'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name azflaskregistry
          docker build -t $(imageName):$(Build.BuildId) .
          docker tag $(imageName):$(Build.BuildId) azflaskregistry.azurecr.io/$(imageName):$(Build.BuildId)
          docker push azflaskregistry.azurecr.io/$(imageName):$(Build.BuildId)

