apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-file-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-file-manager
  template:
    metadata:
      labels:
        app: s3-file-manager
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: flask-s3-app
        image: s3app.azurecr.io/flask-app:IMAGE_TAG_PLACEHOLDER
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: aws-credentials
