apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQTNDNkZNQlJFN1lSQ09XRlQ=
  AWS_SECRET_ACCESS_KEY: dGd3Z1RGVjYwZU9lb1F1anpLMFJsNEYzVUQ3QWlEVTkvUVNQQVJXNw==
